version: '3'
services:
  jellystat-db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sosbrigade1!
    volumes:
    - /postgres-data:/var/lib/postgresql/data # Mounting the volume
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sosbrigade1!
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'Sosbrigade1!'
    ports:
      - "3011:3000" #Server Port
    volumes:
      - /backup-data:/app/backend/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:
